const mongoose=require("mongoose");

const userSchema=new mongoose.Schema({
    firstName:{
        type:"String",
        required:true
    },
    lastName:{
        type:"String",
        required:true
    },
    email:{
        type:"String",
        required:true
    },
    password:{
        type:String,
        required:true
    },
    image:{
        type:String,
        required:true
    },
    active:{
        type:Boolean,
        default:true
    },
    approved:{
        type:String,
        default:true    
    },
    token:{
        type:String
    },
    resetPasswordExpires:{
        type:Date
    },
    token:{
        type:String,
    },
    resetPasswordExpires:{
        type:Date,
    },
    accountType:{
        type:String,
        enum:["Student","Admin","Instructor"],
        required:true
    },
    courses:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"Course"
        }
    ],
    courseProgress:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"CourseProgress"
        }
    ],
    additionalDetails:{
        type:mongoose.Schema.Types.ObjectId,
        required:true,
        ref:"Profile"
    }
},  // Add timestamps for when the document is created and last modified
    { timestamps: true }
);

module.exports=mongoose.model("User",userSchema);